name = "qimochi-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "api.qimochi.web.id/*", zone_name = "qimochi.web.id" }
]

[vars]
ALLOWED_ORIGIN = "https://qimochi.web.id"
GOOGLE_CLIENT_ID = "98346168648-ferhj5ams83nirq87qtjoatl71g8qg5s.apps.googleusercontent.com"

[[d1_databases]]
binding = "DB"
database_name = "qimochi-db"
database_id = "9d6d7f39-3af8-4167-9db7-b9e0a64fdef9"

[observability]
enabled = true
