name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            TELEGRAM_BOT_TOKEN
            GH_WEBHOOK_SECRET
            ADMIN_CHAT_ID
            DISCORD_WEBHOOK_GISCUS
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
          DISCORD_WEBHOOK_GISCUS: ${{ secrets.DISCORD_WEBHOOK_GISCUS }}